coffees = [
    {'id': 0,
     'name': 'BrewBlack Coffee Pods',
     'collection': 'Crema',
     'intensity': '8',
     'numbers': '20'},
    {'id': 1,
     'name': 'BrewBlack Coffee Pods',
     'collection': 'Ristretto',
     'intensity': '10',
     'numbers': '20'},
    {'id': 2,
     'name': 'BrewBlack Coffee Pods',
     'collection': 'Perfetto',
     'intensity': '9',
     'numbers': '20'},
    {'id': 3,
     'name': 'BrewBlack Coffee Pods',
     'collection': 'Intenso',
     'intensity': '12',
     'numbers': '19'},
    {'id': 4,
     'name': 'BrewBlack Coffee Pods',
     'collection': 'Supremo',
     'intensity': '9',
     'numbers': '20'},
]